### ISSUE TITLE
ежжи не работает я жЕ вижу что ты в онлайне

### ISSUE THREAD

**Issue by andreidevo** [enoki1/some-scripts#1]
Добрый день

**Comment by oush7** [comment]
АХАХХАХАХАХАХАХАХАХХАХАХАХАХАХАХАХАХХАХАХАХАХАХАХАХАХАХАХХАХАХАХАХАХАХАХАХАХАХХАХАХАХАХАХАХАХАХАХХАХАХАХАХАХАХАХАХАХАХАХАХААХАХАХХАХАХАХАХАХАХАХАХАХАХАХХАХАХАХХАХАХА ДА🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡27.05.2022, 17:03, "Andrei Novatov" ***@***.***>:
Добрый день, дорогие разработчики!
Сегодня запускал этот проект на лИцензионном сайте с сертификатиками и у нас всё удалилось с сайта,
можно узнать, это траян? вы замаскировали траян под блокчейном ????
ОТВЕЧАЙТЕ!!!!!!!!!!!!!!!!
